### ISSUE TITLE
Deploy하고 나서 local 환경에서 테스트하면, 테마의 vendor,css 로딩이 안됩니다.

### ISSUE THREAD

**Issue by progresivoJS** [HyunSeob/hexo-theme-overdose#7]
우선 저는 cloud ide에서 local환경을 꾸며서 만들고 있습니다.
따라서 localhost 가 저에게는 https://progresivo_blogg.goorm.io/ 입니다.
이점 유의하고 봐주세요!

![image](https://cloud.githubusercontent.com/assets/22091806/18815735/e9b99862-8373-11e6-8393-ab04d5232c88.png)

github page에 deploy를 하고나서, `hexo s` 로 local환경에서 돌려보니까, 위와같이 vendor랑 css를 전혀 불러오지 못하네요.

경로 문제인거같은데 어떻게 해결하나요?

_config.yml 의 일부는 다음과 같습니다.

```
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://progresivoJS.github.io/progresivoJS.github.io
root: /progresivoJS.github.io/
#url: http://yoursite.com
#root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
```

그런데 한번 deploy하고나니까 다시 url과 root를 원래대로 고쳐도 (주석처리된 두줄) 안됩니다..
원래 대로 고쳤더니,
![image](https://cloud.githubusercontent.com/assets/22091806/18815763/70b51706-8374-11e6-9298-80ca021be7ed.png)
다음과 같이 나오더라구요.
계속해서 /progresivoJS.github.io 에 요청을 합니다.
/ 루트 디렉토리(https://progresivo_blogg.goorm.io/)에 요청을 해도, 다시 위 그림처럼 https://progresivo_blogg.goorm.io/progresivoJS.github.io/ 로 redirecting이 됩니다. 이유를 알수있을까요..
progresivoJS.github.io에 관한 설정을 지웠는데도 저렇게 되는 이유가 뭘까요... 도와주십쇼!

테마 정말 잘쓰고있습니다.

**Comment by HyunSeob** [comment]
@progresivoJS
안녕하세요. 먼저 잘 사용해주셔서 감사합니다.
제가 생각하기에는 _config.yml의 root path 지정이 잘못된 것 같습니다.

``` yml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://hyunseob.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
```

제 블로그 설정을 참고해주세요. 저는 root path를 `/`로 지정했습니다.
