### ISSUE TITLE
Timezone is not working.

### ISSUE THREAD

**Issue by progresivoJS** [HyunSeob/hexo-theme-overdose#9]
```
# Site
title: Progresivo Developer
subtitle: Home
description: progresivoJS's Blog
author: progresivoJS
language:
timezone: Asia/Seoul
```

config.yml이 이렇게 되어있는데,

```
title: test2
banner:
  url: /images/default.jpg
  width: 1280
  height: 720
categories:
  - Blog
  - Hexo
tags:
  - Hexo
date: 2016-09-26 14:02:04
```

hexo new "test2" 했을때 위와같이 생성이 됩니다.
저는 23:02 에 생성했음에도 불구하고 -9시간인 14:02 라고 자동 생성되네요.

scaffods에는

```

---
title: {{ title }}
date: {{ date }}
banner:
  url: /images/default.jpg
  width: 1280
  height: 720
categories:
  - Blog
  - Hexo
tags:
  - Hexo

---
```

이런식으로 정의되어 있구요. 무엇이 문제일까요?

@HyunSeob 님 블로그 보니까, Timezone이 잘 먹히고 있는거 같은데 저는 뭐가 문제일까요?
